CREATE TABLE IF NOT EXISTS public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    age integer NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    country varchar(50) NOT NULL,
    postal_code varchar(50) NULL,
    pet_category varchar(20) NOT NULL,
    pet_name varchar(50) NOT NULL,
    pet_breed varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sellers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    country varchar(50) NOT NULL,
    postal_code varchar(50) NULL
);

CREATE TABLE IF NOT EXISTS public.suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    contact varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    phone varchar(50) NOT NULL UNIQUE,
    location varchar(50) NOT NULL,
    city varchar(50) NOT NULL,
    country varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    supplier_id integer REFERENCES public.suppliers(id),
    category varchar(50) NOT NULL,
    pet_category varchar(50) NOT NULL,
    brand varchar(50) NOT NULL,

    price real NOT NULL,
    quantity integer NOT NULL,
    weight real NOT NULL,
    color varchar(50) NOT NULL,
    size varchar(20) NOT NULL,

    material varchar(50) NOT NULL,
    description text NOT NULL,
    rating real NOT NULL,
    reviews integer NOT NULL,

    released_at date NOT NULL,
    expiring_at date NOT NULL
);

CREATE TABLE IF NOT EXISTS public.stores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    state varchar(50) NULL,
    phone varchar(50) NOT NULL UNIQUE,
    email varchar(50) NOT NULL UNIQUE,
    location varchar(50) NOT NULL,
    city varchar(50) NOT NULL,
    country varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sales (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    customer_id integer REFERENCES public.customers(id),
    seller_id integer REFERENCES public.sellers(id),
    product_id integer REFERENCES public.products(id),
    store_id integer REFERENCES public.stores(id),
    quantity integer NOT NULL,
    total_price real NOT NULL
);